activation: 0
attention: none
frames_in: 3
frames_out: 5
kernel_size: !!python/tuple
- 3
- 3
- 3
loss_weights:
  energy_loss: 0.0
  recon_loss: 1.0
  space_grad_loss: 1.0
  time_grad_loss: 1.0
lr: 0.001
n_filters: 16
n_layers: 20
profile: false
residual_step: 5
step: 5
